name: build
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.pdn"
      - ".github/FUNDING.yml"
  push:
    branches:
      - "main"
      - "mc/**"
    paths-ignore:
      - "**/*.md"
      - "**/*.pdn"
      - ".github/FUNDING.yml"

env:
  APPEND_BUILD_NUMBER: true

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build --no-daemon

      - name: capture 1.20.4 build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-1.20.4
          path: modules/fabric-1.20.4/build/libs/

      - name: capture 1.21.0 build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-1.21.0
          path: modules/fabric-1.21.0/build/libs/
